#!/usr/bin/env python3
"""Regenerate/check pinned Emoji_Modifier properties offline; output to stdout."""

import argparse
import hashlib
from pathlib import Path
import re
import sys

UNICODE_VERSION = "18.0.0"
DATA_SHA256 = "80d00f8e616a0ef27fd6b8de3b758c06383b5d917e2977709578e68baf733bf1"
DATA_URL = f"https://www.unicode.org/Public/{UNICODE_VERSION}/ucd/emoji/emoji-data.txt"
ROOT = Path(__file__).resolve().parent


def generate(data_path):
    data = data_path.read_bytes()
    if hashlib.sha256(data).hexdigest() != DATA_SHA256:
        raise ValueError("Unicode18 emoji-data SHA256 mismatch")
    properties = {"Emoji_Modifier_Base": [], "Emoji_Modifier": []}
    text = data.decode("utf-8")
    if f"# Version: {UNICODE_VERSION}" not in text.splitlines():
        raise ValueError("Emoji property Unicode version mismatch")
    for line in text.splitlines():
        body = line.split("#", 1)[0].strip()
        if not body:
            continue
        chars, prop = (part.strip() for part in body.split(";"))
        if prop not in properties:
            continue
        if not re.fullmatch(r"[0-9A-F]+(?:\.\.[0-9A-F]+)?", chars):
            raise ValueError(f"Invalid property range: {chars}")
        bounds = chars.split("..")
        first, last = int(bounds[0], 16), int(bounds[-1], 16)
        previous = properties[prop]
        if first > last or (previous and first <= previous[-1][1]):
            raise ValueError(f"Unsorted/overlapping {prop} ranges")
        previous.append((first, last))
    if (len(properties["Emoji_Modifier_Base"]) != 51 or
            sum(last - first + 1 for first, last in properties["Emoji_Modifier_Base"]) != 136 or
            properties["Emoji_Modifier"] != [(0x1F3FB, 0x1F3FF)]):
        raise ValueError("Unexpected pinned Emoji_Modifier property cardinality")
    lines = [
        "// Generated by generate_emoji_properties.py; do not edit manually.",
        f"// Unicode version: {UNICODE_VERSION}",
        f"// Source: {DATA_URL}",
        f"// SHA256: {DATA_SHA256}",
        "// Copyright © 1991-2026 Unicode, Inc. Unicode License V3.",
        "// Full notice: tui/cmake/unicode/UNICODE-LICENSE.txt.",
        "// Modified from the original data: only these two properties are extracted.",
        "// Included after Interval inside string.cpp's anonymous namespace.",
    ]
    for prop, name in (("Emoji_Modifier_Base", "g_emoji_modifier_bases18"),
                       ("Emoji_Modifier", "g_emoji_modifiers18")):
        ranges = properties[prop]
        lines.append(f"constexpr std::array<Interval, {len(ranges)}> {name} = {{{{")
        lines.extend(f"    {{0x{first:x}, 0x{last:x}}}," for first, last in ranges)
        lines.append("}};")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data", type=Path, default=ROOT / "unicode/emoji-data-18.0.0.txt")
    parser.add_argument("--check", action="store_true", help="verify the checked-in generated table")
    args = parser.parse_args()
    try:
        generated = generate(args.data)
        if args.check:
            table = ROOT / "unicode/emoji_properties_18.inc"
            if table.read_bytes() != generated.encode("utf-8"):
                raise ValueError("Generated emoji table is stale")
            print("Unicode18 emoji property generation: exact match")
        else:
            sys.stdout.write(generated)
    except (OSError, UnicodeError, ValueError) as error:
        print(error, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
